import type { Metadata } from 'next'
import Footer from '@/components/Footer';
import Navbar from '@/components/navbar';
import { Inter as FontSans   } from 'next/font/google'
import './globals.css'
import { cn } from "../lib/utils"

const fontSans  = FontSans ({ 
  subsets: ['latin'], 
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}><Navbar/>
          {children}
        
        <Footer/>
        </body>
    </html>
  )
}
